#!/bin/bash


source /init/env/data
source /init/lib/package.sh
source /init/lib/setconf.sh
source /init/lib/spolicy.sh


### CONFIG
prepare_configuration_blackbird_basic

### USERS
register_user_masters_blackbird_basic
register_user_siteman_blackbird_basic
register_user_adminer_blackbird_basic

### INSTALL
install_package_aurs_blackbird_basics

### CONFIG
config_package_main_blackbird_kernels
config_package_main_blackbird_network
config_package_main_blackbird_secured

### policy
blackbird_cis_level_2_policy_install

mkinitcpio -P
exit